### ISSUE TITLE
Get A Shopcart API

### ISSUE THREAD

**Issue by nijya** [CSCI-GA-2820-SU23-001/shopcarts#5]
> Author: Wan-Yu Lin @wl2484

**As a** developer
**I need** to create an API to get the shopcart content of a given customer
**So that** user can browse his/her shopcart content
   
 ### Details and Assumptions
> [discussion thread](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW)
1. Assumed corresponding database model for shopcarts is available and accessible.
2. The API should be implemented using the REST architectural style.
3. The API should follow the standard HTTP methods, with the READ operation using the **GET** method.
4. **The API should log necessary actions for debugging**
5. The endpoint for retrieving shopcarts should be **/shopcarts/{shopcart_id}**.
6. **The response body should be in JSON format**.
7. The response body should include the shopcart's details and the list of items in it.
8. The API should return a status code of 200 (OK) for successful retrieval.
9. **The API should include appropriate error handling** for invalid requests such as shopcarts that do not exist and internal error.
10. **Instructions on how to use the API, including the endpoint, parameters, and expected response format should be updated to README.md.**
   
 ### Acceptance Criteria
```gherkin
// Happy Path or Basic Functionality
Given a request to read a shopcart content,
When the API is called with an valid shopcart ID,
Then the API should respond with a status code of 200 (OK),
And the JSON response body should contain the details of the requested shopcart and the list of items in it.

// Error Handling
Given a request to read a shopcart content,
When the API is called with the invalid or non-existent shopcart ID,
Then the API should respond with a status code of 404 (Not Found),
And the response body should contain an error message indicating that the requested shopcart does not exist.

Given a request to read a shopcart by ID that encounters a database or internal failure,
When the API is called with an valid shopcart ID,
Then the API should respond with a status code of 500 (Internal Server Error),
And the response body should contain an error message indicating the failure to retrieve the shopcart due to a database or internal issue.

// Documentation
Given the API documentation, i.e. README.md,
When developers or consumers refer to it,
Then the documentation should provide clear instructions on how to use the API, including the endpoint, parameters, and expected response format,
And the documentation should include examples and sample requests to assist users in understanding the API.
```

**Comment by wl2484** [comment]
**As a** developer
**I need** to create an API to return a list of items in the shopcart of a given customer
**So that** user can browse the items in their shopcart
   
 ### Details and Assumptions
1. Assumed corresponding database model for shopcarts is available and accessible.
2. The API should be implemented using the REST architectural style.
3. The API should follow the standard HTTP methods, with the READ operation using the GET method.
4. The endpoint for retrieving shopcarts should be /api/customers/{customer_id}/shopcarts.
5. The response should be in JSON format.
6. The response should include the shopcarts' details, such as item names, quantities, prices, and any other relevant information.
7. The API should return a status code of 200 (OK) for successful retrieval.
8. The API should include appropriate error handling for invalid requests, missing parameters, or shopcarts that do not exist.
9. Instructions on how to use the API, including the endpoint, parameters, and expected response format should be updated to README.md.
   
 ### Acceptance Criteria 
1. Assumed corresponding database model for shopcarts is available and accessible.
2. The API should be implemented using the REST architectural style.
3. The API should follow the standard HTTP methods, with the READ operation using the GET method.
4. The endpoint for listing shopcarts should be /api/shopcarts/{customer_id}/items.
5. The response should be in JSON format.
6. The API should return a status code of 200 (OK) for successful retrieval.
7. The response body should include the shopcarts' details, such as item names, quantities, prices, and any other relevant information.
8. The API should handle any potential errors or exceptions during the listing process and respond with appropriate error messages and status codes.
9. Instructions on how to use the API, including the endpoint, parameters, and expected response format should be updated to README.md.
   
```gherkin
// Happy Path or Basic Functionality
Given a valid request to retrieve shopcart items,
When the API is called with the appropriate endpoint and parameters,
Then the API should respond with a status code of 200 (OK).
And the response body should include a list of shopcarts along with their details, such as item names, quantities, prices, etc.

// Error Handling
Given a request to retrieve shopcarts that do not exist (e.g. customer_id does not exist),
When the API is called with the appropriate parameters,
Then the API should respond with a status code of 404 (Not Found).
And the response body should contain an error message indicating that the requested shopcarts were not found.

// Testing
Given a set of mock shopcarts in the database,
When the API is called to list shopcarts,
Then the API response should match the expected shopcarts based on the provided test data.
And unit tests should be written to verify the correctness of the API implementation.

// Documentation
Given the API documentation, i.e. README.md,
When developers or consumers refer to it,
Then the documentation should provide clear instructions on how to use the API, including the endpoint, parameters, and expected response format.
And the documentation should include examples and sample requests to assist users in understanding the API.
```

**Comment by wl2484** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/5?planning-poker) with Zenhub @LillisLuo @momo100110 @nijya @wl2484

**Comment by wl2484** [comment]
Based on [Professor's response](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW), the Read shopcarts API actually implies 2 APIs:
`GET /shopcarts/{shopcart_id}` to get a shopcart by shopcart_id
`GET /shopcarts/{shopcart_id}/items/{item_id}` to get item details in a shopcart (such as name, unit price, and quantity) by shopcart_id and item_id

I feel like it's better to create 2 separate stories for different APIs?

**Comment by wl2484** [comment]
Updated the description for the assignee's convenience!
